apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: ekart-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekart-app
  template:
    metadata:
      labels:
        app: ekart-app
    spec:
      containers:
      - name: ekart-app
        image: 
        ports:
        - containerPort: 8080
